#!/usr/bin/env sh
ln -s $PWD/fish ~/.config/fish/config.fish
ln -s $PWD/i3 ~/.config/i3/config
ln -s $PWD/x/init ~/.xinitrc
ln -s $PWD/x/resources ~/.Xresources
ln -s $PWD/polybar ~/.config/polybar/config
ln -s $PWD/mpv ~/.config/mpv/mpv.conf
ln -s $PWD/git ~/.gitconfig
ln -s $PWD/git-pass ~/.config/pass-git-helper/git-pass-mapping.ini
ln -s $PWD/vim ~/.vimrc
ln -s $PWD/code ~/.config/Code/User/settings.json
ln -s $PWD/dunst ~/.config/dunst/dunstrc
ln -s $PWD/lock ~/bin/lock
